### ISSUE TITLE
Tables should not be created if bundles are not installed

### ISSUE THREAD

**Issue by rabauss** [hofff/contao-social-tags#25]
Currently, if you don't have the calendar, faq, or news bundles installed, the extension still creates the tables.
That should be stopped!

 Or is that a bug of the core? because this has only happened since contao 4.13!

**Comment by dmolineus** [comment]
I guess it's caused by https://github.com/contao/contao/pull/4285 and all related issues. I think this is a huge BC break of Contao as until now it was possible to ship dca files which does not set the dc driver and everything was fine.

Could you create an issue at Contao please to clarify the issue?

**Comment by dmolineus** [comment]
Contao decided to revert the changes. So we won't do anything here.
